version: '3.4'

services:
  githubstatusbot:
    image: githubstatusbot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GH_CHANNEL=${GH_CHANNEL}

